services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - DATABASE_URL=${DATABASE_URL}
    container_name: next-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DATABASE_URL=mongodb://mongodb:27017/jetschooldb?replicaSet=rs0

    depends_on:
      - mongodb
    networks:
      - jetschool
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  api:
    build: ./api
    container_name: nest-app
    restart: always
    ports:
      - "3001:3002"
    env_file:
      - .env
    volumes:
      - ~/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - jetschool

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - jetschool
    command: ["--replSet", "rs0", "--bind_ip_all", "--noauth"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - client
      - api
    networks:
      - jetschool

volumes:
  mongodata:

networks:
  jetschool:
    driver: bridge
