services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_CDN_URL=${NEXT_PUBLIC_CDN_URL}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - DATABASE_URL=${DATABASE_URL}
    container_name: next-app-acad
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DATABASE_URL=mongodb://mongodb:27017/jetschooldb?replicaSet=rs0

    depends_on:
      - mongodb
    networks:
      - jetschool
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  api:
    build: ./api
    container_name: nest-app-acad
    restart: always
    ports:
      - "3001:3002"
    env_file:
      - .env
    volumes:
      - ~/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - jetschool

networks:
  jetschool:
    driver: bridge
